// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKM7tZvCp08y_-vNUCw3196RVJ3UEPgM0',
    appId: '1:804906482484:web:55674415d2e80be8668361',
    messagingSenderId: '804906482484',
    projectId: 'techrelieve-90c12',
    authDomain: 'techrelieve-90c12.firebaseapp.com',
    storageBucket: 'techrelieve-90c12.firebasestorage.app',
    measurementId: 'G-KBWTSGM8WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLKMKklWT12uKDQETyG-MTX5XKAxP-qfs',
    appId: '1:804906482484:android:0695a0b6a17e68a5668361',
    messagingSenderId: '804906482484',
    projectId: 'techrelieve-90c12',
    storageBucket: 'techrelieve-90c12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIOlUY5cQ6MkK1dhasK5IvWxIG5AmYamo',
    appId: '1:804906482484:ios:5cf337a17b5ac48d668361',
    messagingSenderId: '804906482484',
    projectId: 'techrelieve-90c12',
    storageBucket: 'techrelieve-90c12.firebasestorage.app',
    iosBundleId: 'com.example.RatNawnAIApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIOlUY5cQ6MkK1dhasK5IvWxIG5AmYamo',
    appId: '1:804906482484:ios:5cf337a17b5ac48d668361',
    messagingSenderId: '804906482484',
    projectId: 'techrelieve-90c12',
    storageBucket: 'techrelieve-90c12.firebasestorage.app',
    iosBundleId: 'com.example.RatNawnAIApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKM7tZvCp08y_-vNUCw3196RVJ3UEPgM0',
    appId: '1:804906482484:web:8a8efdcf8213c47c668361',
    messagingSenderId: '804906482484',
    projectId: 'techrelieve-90c12',
    authDomain: 'techrelieve-90c12.firebaseapp.com',
    storageBucket: 'techrelieve-90c12.firebasestorage.app',
    measurementId: 'G-FZ8ZWMLDMB',
  );

}